version: '3'
services:
  web:
    build:
      target: web-image
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - web-init
  web-init:
    build:
      target: alembic-image
      context: .
    volumes:
      - .:/usr/src/app
    environment:
      - DB_URI=postgresql://postgres:postgres@db:5432
    depends_on:
      db:
        condition: service_healthy
  db:
    image: 'postgres:14.1'
    user: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
